"""Home Assistant entities generated by the Guards module.

The platform files (``sensor.py``, ``switch.py``, ``number.py``) call one
builder each. The Home Assistant base classes are imported with fallbacks
so that a platform module can still be imported by the unit tests, which
stub only the platform under test.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import TYPE_CHECKING, Any

from homeassistant.core import HomeAssistant

try:
    from homeassistant.components.number import NumberEntity, NumberMode
except ImportError:  # pragma: no cover - partial test stubs
    NumberEntity = object  # type: ignore[assignment,misc]
    NumberMode = SimpleNamespace(BOX="box")  # type: ignore[assignment]
try:
    from homeassistant.components.sensor import SensorDeviceClass, SensorEntity
except ImportError:  # pragma: no cover - partial test stubs
    SensorEntity = object  # type: ignore[assignment,misc]
    SensorDeviceClass = SimpleNamespace(ENUM="enum")  # type: ignore[assignment]
try:
    from homeassistant.components.switch import SwitchEntity
except ImportError:  # pragma: no cover - partial test stubs
    SwitchEntity = object  # type: ignore[assignment,misc]
try:
    from homeassistant.helpers.entity import EntityCategory
except ImportError:  # pragma: no cover - partial test stubs
    EntityCategory = SimpleNamespace(CONFIG="config", DIAGNOSTIC="diagnostic")  # type: ignore[assignment]

from .config_helpers import get_configured_climate_entities
from .entity import VelairEntity
from .guards_models import GUARDS_STATES, normalize_guards_settings

if TYPE_CHECKING:  # pragma: no cover - typing only
    from . import VelairConfigEntry

GUARDS_GLOBAL_NUMBERS: tuple[tuple[str, int, int], ...] = (
    # (field, min, max); every field is a whole number of minutes.
    ("never_off_grace_minutes", 1, 1440),
    ("never_off_snooze_minutes", 1, 10080),
    ("manual_lease_minutes", 0, 1440),
    ("manual_release_vacant_minutes", 1, 1440),
)
ZONE_GUARD_SENSOR_SUFFIX = "guard_state"
ZONE_GUARD_ATTRIBUTES = (
    "grace_ends_at",
    "snooze_until",
    "manual_since",
    "manual_release_at",
    "activity_entity_id",
    "grace_started_at",
    "previous_target",
    "occupancy_entity_id",
    "pause_ids",
    "next_transition_at",
    "last_action",
    "last_action_at",
    "never_off_enabled",
    "manual_release_enabled",
)


def build_guards_sensor_entities(
    hass: HomeAssistant, entry: VelairConfigEntry
) -> list[SensorEntity]:
    """Build one guard state sensor per managed climate."""
    return [
        ZoneGuardSensor(entry, entity_id, zone_name=_climate_name(hass, entity_id))
        for entity_id in get_configured_climate_entities(entry)
    ]


def build_guards_switch_entities(
    hass: HomeAssistant, entry: VelairConfigEntry
) -> list[SwitchEntity]:
    """Build the global Guards master switch."""
    return [GuardsSwitch(entry)]


def build_guards_number_entities(
    hass: HomeAssistant, entry: VelairConfigEntry
) -> list[NumberEntity]:
    """Build the global Guards parameter numbers."""
    return [
        GuardsParameterNumber(entry, field, minimum, maximum)
        for field, minimum, maximum in GUARDS_GLOBAL_NUMBERS
    ]


class ZoneGuardSensor(VelairEntity, SensorEntity):
    """Sensor exposing the Guards state for one zone."""

    _attr_device_class = SensorDeviceClass.ENUM
    _attr_options = list(GUARDS_STATES)
    _attr_translation_key = "zone_guard"

    def __init__(
        self,
        entry: VelairConfigEntry,
        climate_entity_id: str,
        *,
        zone_name: str | None = None,
    ) -> None:
        """Initialize the guard sensor."""
        self._climate_entity_id = climate_entity_id
        zone_key = climate_entity_id.replace(".", "_")
        super().__init__(entry, f"{zone_key}_{ZONE_GUARD_SENSOR_SUFFIX}")
        self._attr_translation_placeholders = {"zone": zone_name or climate_entity_id}

    @property
    def available(self) -> bool:
        """Hide the projection while scheduler data is blocked."""
        return not bool(getattr(self.scheduler, "temperature_migration_blocked", False))

    def _status(self) -> dict[str, Any]:
        getter = getattr(self.scheduler, "get_guards_status", None)
        status = getter(self._climate_entity_id) if callable(getter) else {}
        return status if isinstance(status, dict) else {}

    @property
    def native_value(self) -> str:
        """Return the current guard state."""
        value = self._status().get("state")
        return value if isinstance(value, str) and value in GUARDS_STATES else "idle"

    @property
    def extra_state_attributes(self) -> dict[str, Any] | None:
        """Return compact guard context."""
        status = self._status()
        attributes = {
            key: status.get(key)
            for key in ZONE_GUARD_ATTRIBUTES
            if status.get(key) is not None and status.get(key) != []
        }
        attributes["climate_entity_id"] = self._climate_entity_id
        return attributes


class GuardsSwitch(VelairEntity, SwitchEntity):
    """Master switch for every Guards rule."""

    _attr_translation_key = "guards"

    def __init__(self, entry: VelairConfigEntry) -> None:
        """Initialize the master switch."""
        super().__init__(entry, "guards_enabled")

    @property
    def available(self) -> bool:
        """Hide the switch while scheduler data is blocked."""
        return not bool(getattr(self.scheduler, "temperature_migration_blocked", False))

    @property
    def is_on(self) -> bool:
        """Return whether Guards are enabled."""
        return bool(_stored_settings(self._entry)["enabled"])

    async def async_turn_on(self, **kwargs) -> None:
        """Enable Guards."""
        await self._async_set_enabled(True)

    async def async_turn_off(self, **kwargs) -> None:
        """Disable Guards."""
        await self._async_set_enabled(False)

    async def _async_set_enabled(self, enabled: bool) -> None:
        current = _raw_settings(self._entry)
        await self.scheduler.async_update_settings(
            {"guards": {**current, "enabled": enabled}}
        )


class GuardsParameterNumber(VelairEntity, NumberEntity):
    """Number exposing one global Guards parameter (minutes)."""

    _attr_entity_category = EntityCategory.CONFIG
    _attr_mode = NumberMode.BOX
    _attr_native_unit_of_measurement = "min"
    _attr_native_step = 1.0

    def __init__(
        self,
        entry: VelairConfigEntry,
        field: str,
        minimum: int,
        maximum: int,
    ) -> None:
        """Initialize one parameter number."""
        super().__init__(entry, f"guards_{field}")
        self._field = field
        self._attr_translation_key = f"guards_{field}"
        self._attr_native_min_value = float(minimum)
        self._attr_native_max_value = float(maximum)

    @property
    def available(self) -> bool:
        """Hide the number while scheduler data is blocked."""
        return not bool(getattr(self.scheduler, "temperature_migration_blocked", False))

    @property
    def native_value(self) -> float | None:
        """Return the stored parameter."""
        value = _stored_settings(self._entry).get(self._field)
        return float(value) if isinstance(value, int | float) else None

    async def async_set_native_value(self, value: float) -> None:
        """Persist a new parameter."""
        current = _raw_settings(self._entry)
        await self.scheduler.async_update_settings(
            {"guards": {**current, self._field: int(round(value))}}
        )


def _raw_settings(entry: VelairConfigEntry) -> dict[str, Any]:
    settings = entry.runtime_data.storage.data.get("settings", {})
    current = settings.get("guards") if isinstance(settings, dict) else None
    return dict(current) if isinstance(current, dict) else {}


def _stored_settings(entry: VelairConfigEntry) -> dict[str, Any]:
    return dict(normalize_guards_settings(_raw_settings(entry)))


def _climate_name(hass: HomeAssistant, entity_id: str) -> str:
    """Return a readable climate name for entity translation placeholders."""
    states = getattr(hass, "states", None)
    state = states.get(entity_id) if states is not None else None
    attributes = getattr(state, "attributes", {}) if state is not None else {}
    friendly_name = attributes.get("friendly_name") if isinstance(attributes, dict) else None
    if isinstance(friendly_name, str) and friendly_name:
        return friendly_name
    return entity_id
